CREATE TABLE employee (
  id SERIAL PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  address VARCHAR(80) NOT NULL,
  city VARCHAR(50) NOT NULL,
  phone INTEGER NOT NULL,
  department VARCHAR(50) NOT NULL
);